# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F3G76aHl1qMlEsHQCEPP55Zs11PfqeSq
"""

kitaplar = [] # Global kitap listesini tanımla

def kitap_ekle():
    print("\n--- Yeni Kitap Ekle ---")
    # Her kitap için istenen bilgiler: ad, yazar, sayfa, yıl
    ad = input("Kitap Adı: ")
    yazar = input("Yazarı: ")
    sayfa = input("Sayfa Sayısı: ")
    yil = input("Basım Yılı: ")

    yeni_kitap = {
        "ad": ad,
        "yazar": yazar,
        "sayfa": sayfa,
        "yil": yil,
        "durum": "Mevcut" # Ödünç işlemleri için durum bilgisi
    }
    kitaplar.append(yeni_kitap)
    print(f"'{ad}' başarıyla eklendi.")

def kitap_listele():
    print("\n--- Kütüphane Listesi ---")
    if not kitaplar:
        print("Kütüphanede henüz kitap yok.")
    else:
        for i, kitap in enumerate(kitaplar, 1):
            print(f"{i}. {kitap['ad']} - {kitap['yazar']} ({kitap['yil']}) - Durum: {kitap['durum']}")

def kitap_sil():
    kitap_listele()
    if kitaplar:
        index = int(input("\nSilmek istediğiniz kitabın numarasını girin: ")) - 1
        if 0 <= index < len(kitaplar):
            silinen = kitaplar.pop(index)
            print(f"'{silinen['ad']}' sistemden silindi.")
        else:
            print("Geçersiz numara!")

def odunc_ver():
    kitap_listele()
    ad = input("\nÖdünç verilmek istenen kitabın tam adını yazın: ")
    for kitap in kitaplar:
        if kitap['ad'].lower() == ad.lower() and kitap['durum'] == "Mevcut":
            kitap['durum'] = "Ödünç Verildi"
            print(f"'{ad}' başarıyla kullanıcıya (User) verildi.")
            return
    print("Kitap bulunamadı veya zaten ödünç verilmiş.")

def geri_al():
    ad = input("\nGeri alınan kitabın adını yazın: ")
    for kitap in kitaplar:
        if kitap['ad'].lower() == ad.lower() and kitap['durum'] == "Ödünç Verildi":
            kitap['durum'] = "Mevcut"
            print(f"'{ad}' sisteme geri kaydedildi.")
            return
    print("Bu isimde ödünç verilmiş bir kitap bulunamadı.")

# Ana Menü Döngüsü
while True:
    print("\n--- Kütüphane Yönetim Sistemi (Prosedürel) ---")
    print("1-Kitap Ekle\n2-Kitap Sil\n3-Listele\n4-Odunc Kitap Ver\n5-Geri Al\n6-Çıkış")
    secim = input("Seçiminiz: ")

    if secim == '1': kitap_ekle()
    elif secim == '2': kitap_sil()
    elif secim == '3': kitap_listele()
    elif secim == '4': odunc_ver()
    elif secim == '5': geri_al()
    elif secim == '6':
        print("Programdan çıkılıyor...")
        break
    else:
        print("Geçersiz seçim!")