# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjH5mGjFlBT_mH6-NtWTAPsKp4o-j5Yb
"""

class Book:
    def __init__(self, ad, yazar, sayfa, yil):
        # Öznitelikler (Attributes) - En az 3 tane
        # Alt tire (_) kullanarak verileri korumaya aldık (Encapsulation)
        self._ad = ad
        self._yazar = yazar
        self._sayfa = sayfa
        self._yil = yil
        self._durum = "Mevcut"

    # Getter Metotları (Korumalı veriye erişim)
    @property
    def ad(self):
        return self._ad

    @property
    def durum(self):
        return self._durum

    # Setter Metodu (Veriyi kontrollü değiştirme)
    @durum.setter
    def durum(self, yeni_durum):
        self._durum = yeni_durum

    # ÖZEL METOT (MAGIC METHOD) - Nesne yazdırıldığında çalışır
    def __str__(self):
        return f"📖 {self._ad} - {self._yazar} ({self._yil}) | Durum: {self._durum}"

    # ÇOK BİÇİMLİLİK (POLYMORPHISM) için metot
    def display_info(self):
        print(f"[KİTAP BİLGİSİ]: '{self._ad}' isimli eser {self._yazar} tarafından yazılmıştır.")

# 2. KALITIM (INHERITANCE)
class User:
    def __init__(self, isim, user_id):
        self.isim = isim
        self.user_id = user_id

    def display_info(self): # Polymorphism
        print(f"[KULLANICI]: {self.isim} (ID: {self.user_id})")

# Admin sınıfı User sınıfından miras alır
class Admin(User):
    def __init__(self, isim, user_id, yetki_seviyesi):
        # super() ile üst sınıfın yapıcısını (constructor) çağırıyoruz
        super().__init__(isim, user_id)
        self.yetki_seviyesi = yetki_seviyesi

    # Polymorphism: Aynı isimli metot Admin için farklı çalışır (Overriding)
    def display_info(self):
        print(f"[YÖNETİCİ]: {self.isim} | Yetki: {self.yetki_seviyesi} | ID: {self.user_id}")

# 3. SİSTEM YÖNETİM SINIFI
class Library:
    def __init__(self):
        # Liste yapısı kullanımı zorunluluğu
        self.kitaplar = []

    def kitap_ekle(self, kitap):
        self.kitaplar.append(kitap)
        print(f"Sistem: '{kitap.ad}' kütüphaneye başarıyla eklendi.")

    def listele(self):
        print("\n--- KÜTÜPHANE ENVANTERİ ---")
        if not self.kitaplar:
            print("Kütüphane boş.")
        else:
            for kitap in self.kitaplar:
                print(kitap) # __str__ metodu burada devreye girer

    def kitap_sil(self, kitap_adi):
        for kitap in self.kitaplar:
            if kitap.ad.lower() == kitap_adi.lower():
                self.kitaplar.remove(kitap)
                print(f"Sistem: '{kitap_adi}' silindi.")
                return
        print("Sistem: Kitap bulunamadı.")

# --- ANA PROGRAM (Uygulama) ---
if __name__ == "__main__":
    # Kütüphane nesnesi oluşturma
    my_library = Library()

    # Kitap nesneleri oluşturma (Object Creation)
    kitap1 = Book("Nutuk", "M. Kemal Atatürk", 600, 1927)
    kitap2 = Book("Sefiller", "Victor Hugo", 1200, 1862)

    # Kullanıcı ve Admin nesneleri
    user1 = User("Ali", "U101")
    admin1 = Admin("Zeynep", "A001", "Tam Yetki")

    # İşlemler
    my_library.kitap_ekle(kitap1)
    my_library.kitap_ekle(kitap2)
    my_library.kitap_sil(kitap2)
    my_library.listele()

    # Polymorphism Gösterimi
    print("\n--- Çok Biçimlilik (Polymorphism) Testi ---")
    liste = [kitap1, user1, admin1]
    for obje in liste:
        obje.display_info()